excluded:
    - Pods
    - Libraries
    - travelPlanTests/
    - travelPlanUITests/

included:
    
disabled_rules:
    - leading_whitespace
    - trailing_whitespace
    - multiple_closures_with_trailing_closure
    - identifier_name
    
line_length:
  ignores_comments: true

