excluded:
    - Pods
    - "**/*Tests.swift"
    - Libraries
    - travelPlanTests/
    - travelPlanUITests/
    - Source/Common/Extension/UIDevice+modelName.swift

included:

disabled_rules:
    - leading_whitespace
    - trailing_whitespace
    - multiple_closures_with_trailing_closure
    - identifier_name
    - type_name
    - file_length
    - line_length


line_length:
  ignores_comments: true

# 엇 왜 적용이..
# https://realm.github.io/SwiftLint/file_length.html
# file_length:
#  min_length: 1200
#  max_length: 1500

function_parameter_count:
  ignored_regex: 'register\('

function_parameter_count:
  ignored_regex: 'resolve\('

nesting:
  type_level:
    warning: 5
    error: 6
  statement_level:
    warning: 5
    error: 10
