excluded:
    - Pods
    - Libraries
    - travelPlanTests/
    - travelPlanUITests/
    - Source/Common/Extension/UIDevice+modelName.swift

included:

disabled_rules:
    - leading_whitespace
    - trailing_whitespace
    - multiple_closures_with_trailing_closure
    - identifier_name
    - type_name
    
line_length:
  ignores_comments: true


nesting:
  type_level:
    warning: 5
    error: 6
  statement_level:
    warning: 5
    error: 10

