# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'travelPlan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for travelPlan
  pod 'SnapKit', '~> 5.6.0'
  pod 'SwiftLint'
  pod 'Alamofire' 

end

target 'travelPlanTests' do
  inherit! :search_paths
end

